//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentariu
    {
        public int Id { get; set; }
        public int PostareId { get; set; }
        public string Titlu { get; set; }
        public string Text { get; set; }
        public string ComentatorId { get; set; }
        public string Nume { get; set; }
        public string Email { get; set; }
        public string SiteWeb { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.DateTime DataCreare { get; set; }
        public bool Edited { get; set; }
        public bool Aprobat { get; set; }
    
        public virtual Postare Postare { get; set; }
    }
}
