//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postare
    {
        public int ID { get; set; }
        public string PostareTXT { get; set; }
        public int UtilizatorID { get; set; }
        public Nullable<int> PozaID { get; set; }
    
        public virtual Poza Poza { get; set; }
        public virtual Utilizator Utilizator { get; set; }
    }
}
