//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMedia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Social_MediaEntities : DbContext
    {
        public Social_MediaEntities()
            : base("name=Social_MediaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Postare> Postares { get; set; }
        public virtual DbSet<Poza> Pozas { get; set; }
        public virtual DbSet<Utilizator> Utilizators { get; set; }
    }
}
