//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstDbModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postare()
        {
            this.Pozas = new HashSet<Poza>();
        }
    
        public int Id { get; set; }
        public int UtilizatorId { get; set; }
        public string Titlu { get; set; }
        public string Descriere { get; set; }
    
        public virtual Utilizator Utilizator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poza> Pozas { get; set; }
    }
}
