//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postare()
        {
            this.Comentarius = new HashSet<Comentariu>();
            this.Pozas = new HashSet<Poza>();
        }
    
        public int Id { get; set; }
        public string Titlu { get; set; }
        public string Text { get; set; }
        public string AutorId { get; set; }
        public System.DateTime DataCreare { get; set; }
        public Nullable<System.DateTime> UltimulUpdate { get; set; }
        public bool Publicata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentariu> Comentarius { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poza> Pozas { get; set; }
    }
}
